"""empty message

Revision ID: 1e4b94940c7c
Revises: d6e225202b35
Create Date: 2025-06-23 21:50:06.970062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4b94940c7c'
down_revision: Union[str, None] = 'd6e225202b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_types', sa.Column('color', sa.Text(), server_default='#e31a1c', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_types', 'color')
    # ### end Alembic commands ###
