"""empty message

Revision ID: 240474d780d3
Revises: 679ec24f866a
Create Date: 2025-05-27 21:10:50.484107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240474d780d3'
down_revision: Union[str, None] = '679ec24f866a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_type',
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name='node_type_node_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], ['node_types.id'], name='node_type_type_id_fkey'),
    sa.UniqueConstraint('node_id', 'type_id', name='unique_node_type')
    )
    # ### end Alembic commands ###
