"""empty message

Revision ID: 37968aa09173
Revises: 1e4b94940c7c
Create Date: 2025-06-23 23:07:19.490188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37968aa09173'
down_revision: Union[str, None] = '1e4b94940c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq__nodes__name_type_id', 'nodes', ['name', 'type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__nodes__name_type_id', 'nodes', type_='unique')
    # ### end Alembic commands ###
