"""empty message

Revision ID: 6113a37ae49a
Revises: 37968aa09173
Create Date: 2025-06-24 20:52:11.296346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6113a37ae49a'
down_revision: Union[str, None] = '37968aa09173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'config', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config', type_='foreignkey')
    op.drop_column('config', 'section_id')
    # ### end Alembic commands ###
