"""empty message

Revision ID: 8ad35c9b215c
Revises: 691202a9ce85
Create Date: 2025-06-04 23:18:15.258067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad35c9b215c'
down_revision: Union[str, None] = '691202a9ce85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_node', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'node_node', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node_node', type_='foreignkey')
    op.drop_column('node_node', 'user_id')
    # ### end Alembic commands ###
