"""empty message

Revision ID: 95d69af35144
Revises: 
Create Date: 2025-05-06 22:56:13.644432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d69af35144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_employees_uuid'), 'employees', ['uuid'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('employee_department',
    sa.Column('employee_uuid', sa.String(), nullable=False),
    sa.Column('departments_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departments_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_uuid'], ['employees.uuid'], ),
    sa.UniqueConstraint('employee_uuid', 'departments_id', name='unique_employee_department')
    )
    op.create_table('employee_employee',
    sa.Column('employee1_uuid', sa.String(), nullable=False),
    sa.Column('employee2_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee1_uuid'], ['employees.uuid'], ),
    sa.ForeignKeyConstraint(['employee2_uuid'], ['employees.uuid'], ),
    sa.UniqueConstraint('employee1_uuid', 'employee2_uuid', name='unique_employee_employee')
    )
    op.create_table('employee_position',
    sa.Column('employee_uuid', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_uuid'], ['employees.uuid'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.UniqueConstraint('employee_uuid', 'position_id', name='unique_employee_position')
    )
    op.create_table('employee_project',
    sa.Column('employee_uuid', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_uuid'], ['employees.uuid'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.UniqueConstraint('employee_uuid', 'project_id', name='unique_employee_project')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_project')
    op.drop_table('employee_position')
    op.drop_table('employee_employee')
    op.drop_table('employee_department')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_employees_uuid'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
