"""empty message

Revision ID: c47ea84bb35f
Revises: 240474d780d3
Create Date: 2025-05-27 21:27:36.038506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47ea84bb35f'
down_revision: Union[str, None] = '240474d780d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'node_types', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'nodes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sections', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('dt_create', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dt_create')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'node_types', type_='foreignkey')
    # ### end Alembic commands ###
