"""empty message

Revision ID: d6e225202b35
Revises: ea940ab329b8
Create Date: 2025-06-05 22:42:33.878494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e225202b35'
down_revision: Union[str, None] = 'ea940ab329b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_node')
    op.drop_constraint('node_types_section_id_fkey', 'node_types', type_='foreignkey')
    op.create_foreign_key(None, 'node_types', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node_types', type_='foreignkey')
    op.create_foreign_key('node_types_section_id_fkey', 'node_types', 'sections', ['section_id'], ['id'])
    op.create_table('section_node',
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name='section_node_node_id_fkey'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='section_node_section_id_fkey'),
    sa.UniqueConstraint('section_id', 'node_id', name='unique_section_node')
    )
    # ### end Alembic commands ###
