"""empty message

Revision ID: ea940ab329b8
Revises: d0958e5255f3
Create Date: 2025-06-05 22:10:36.310737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea940ab329b8'
down_revision: Union[str, None] = 'd0958e5255f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nodes_type_id_fkey', 'nodes', type_='foreignkey')
    op.create_foreign_key(None, 'nodes', 'node_types', ['type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.create_foreign_key('nodes_type_id_fkey', 'nodes', 'node_types', ['type_id'], ['id'])
    # ### end Alembic commands ###
