version: '3.8'

services:
  nginx:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: employee_graph_frontend:0.1.6
    ports:
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee_graph_api:0.1.6
    expose:
      - "8000"
    environment:
      - DB_URL=${DB_URL}
      - SECRET=${SECRET}
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 