version: '3.8'

services:
  nginx:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: employee_graph_frontend:0.1.0
    ports:
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - DB_URL=${DB_URL}
      - SECRET=${SECRET}
    volumes:
      - .:/app
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: dev-postgres
    environment:
      POSTGRES_USER: devpg
      POSTGRES_PASSWORD: devpg
      POSTGRES_DB: dev_employee_graph
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pg_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 