version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - DB_URL=${DB_URL}
      - SECRET=${SECRET}
    volumes:
      - .:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://localhost/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 